name: GitHub Classroom Workflow

on: 
  push:
    branches:
    - '*'
    - '!badges'
    - '!feedback'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # job to run autograding
  build:
    name: Autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      # test activity 1
      - uses: actions/github-script@v4
        name: "Check Activity 1"
        id: activity1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // get repo name
            const repoName = context.repo.repo.toLowerCase()

            // get repo members
            const res = await github.repos.listCollaborators({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            let collaborators = res.data
            console.log(collaborators)

            // check if one of collab list matches repository name suffix. make case insensitive.
            if (collaborators.some(collaborator=>repoName.endsWith(collaborator.login.toLowerCase()))) {
              console.log("found collaborator match to repo suffix")

              // write result to file
              const fs = require('fs');
              fs.writeFile('.github/results/activity1.txt', 'pass', function (err) {
                if (err) return console.log(err);
              });

              return 'success'
            }
            else {
              console.log("no match to repo suffix")
              return 'fail'
            }
      
      # test activity 2
      - uses: actions/github-script@v4
        name: "Check Activity 2"
        id: activity2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // get commits, filtered by actor
            const res = await github.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              author: context.actor,
            });
            let commitList = res.data
            console.log(commitList)

            // is commit list non-zero
            if (Array.isArray(commitList) && commitList.length) {
              console.log("commits found")

              // write result to file
              const fs = require('fs');
              fs.writeFile('.github/results/activity2.txt', 'pass', function (err) {
                if (err) return console.log(err);
              });

              return 'success'
            }
            else {
              console.log(`no commits for ${context.actor} found`)
              return 'fail'
            }


      - run: ls .github/results

      # run grading
      # add id to step so outputs can be referenced
      - uses: education/autograding@v1
        name: "** Grading and Feedback **"
        id: autograder
        continue-on-error: true

      # fail job if autograder returns failed
      # outcome can be 'success', 'failure', 'cancelled', or 'skipped'
      # trigger fail either on !success or on failure depending on preference
      - name: check autograder pass fail
        if: ${{ steps.autograder.outcome != 'success' }}
        run: exit 1

    outputs:
      grading-score: ${{ steps.autograder.outputs.Points }}
      activity1-result: ${{ steps.activity1.outputs.result }}
      activity2-result: ${{ steps.activity2.outputs.result }}
